export const pizzaObject = {
    savoury: {
        toppingsList: [
            "Cheese",
            "Mushroom",
            "Tomato slices",
            "Pineapple",
            "Onion",
        ],
        sauceList: ["Tomato sauce", "Pesto sauce", "BBQ sauce"],
        srcListIcons: [
            "images/icons/dough-icon.png",
            "images/icons/savoury/tomato-sauce-icon.png",
            "images/icons/savoury/pesto-sauce-icon.png",
            "images/icons/savoury/bbq-sauce-icon.png",
            "images/icons/savoury/cheese-icon.png",
            "images/icons/savoury/mushroom-icon.png",
            "images/icons/savoury/pineapple-icon.png",
            "images/icons/savoury/sliced-tomato-icon.png",
            "images/icons/savoury/onion-icon.png",
        ],
        srcListToppings: [
            "images/pizza-toppings/pizza-base-1.png",
            "images/pizza-toppings/savoury/pizza-tomato-1.png",
            "images/pizza-toppings/savoury/pizza-pesto-1.png",
            "images/pizza-toppings/savoury/pizza-bbq.png",
            "images/pizza-toppings/savoury/pizza-cheese-1.png",
            "images/pizza-toppings/savoury/pizza-topping-mushroom-s2.png",
            "images/pizza-toppings/savoury/pizza-topping-pineapple.png",
            "images/pizza-toppings/savoury/tomato-pizza-topping-s2.png",
            "images/pizza-toppings/savoury/onion-pizza-topping-s2.png",
        ],
    },
    sweet: {
        toppingsList: [
            "Blueberries",
            "Chocolate chips",
            "Marshmallows",
            "Strawberries",
            "Sprinkles",
        ],
        sauceList: ["Chocolate Sauce", "Strawberry Sauce", "Caramel Sauce"],
        srcListIcons: [
            "images/icons/dough-icon.png",
            "images/icons/sweet/chocolate-sauce-icon.png",
            "images/icons/sweet/strawberry-sauce-icon.png",
            "images/icons/sweet/caramel-sauce-icon.png",
            "images/icons/sweet/blueberry-icon.png",
            "images/icons/sweet/chocolate-chip-icon.png",
            "images/icons/sweet/marshmallow-icon.png",
            "images/icons/sweet/strawberry-icon.png",
            "images/icons/sweet/sprinkles-icon.png",
        ],
        srcListToppings: [
            "images/pizza-toppings/pizza-base-1.png",
            "images/pizza-toppings/sweet/chocolate-sauce.png",
            "images/pizza-toppings/sweet/strawberry-sauce.png",
            "images/pizza-toppings/sweet/caramel-sauce.png",
            "images/pizza-toppings/sweet/blueberry-topping.png",
            "images/pizza-toppings/sweet/chocolate-chip-topping.png",
            "images/pizza-toppings/sweet/marshmallow-topping.png",
            "images/pizza-toppings/sweet/strawberry-topping.png",
            "images/pizza-toppings/sweet/sprinkles-topping.png",
        ],
    },
};
